#ifndef HYUNDEOK_DOCPARSER_STRUCTS_FIB_FIBRGCSWNEW_FIBRGCSWNEWDATA2000_H
#define HYUNDEOK_DOCPARSER_STRUCTS_FIB_FIBRGCSWNEW_FIBRGCSWNEWDATA2000_H

#define SZ_FIBRGCSWNEWDATA2000 2

typedef struct FibRgCswNewData2000 {
  unsigned int cQuickSavesNew : 16;
} FibRgCswNewData2000;

#endif
